# Generated by Django 3.1 on 2020-12-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetstatus',
            name='status',
            field=models.IntegerField(choices=[(1, 'Актуальная запись'), (0, 'Архивная запись')], default=1, verbose_name='Статус записи'),
        ),
    ]
