# Generated by Django 3.1 on 2020-12-10 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201210_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetstatus',
            old_name='budgettype',
            new_name='budgtypecode',
        ),
        migrations.AlterField(
            model_name='budgetstatus',
            name='code',
            field=models.CharField(max_length=8, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='budgetstatus',
            name='parentcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api.budgetstatus', verbose_name='Вышестоящий бюджет'),
        ),
        migrations.AlterField(
            model_name='budgetstatus',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Актуальная запись'), ('ARCHIVE', 'Архивная запись')], default='ACTIVE', max_length=7, verbose_name='Статус записи'),
        ),
    ]
