# Generated by Django 3.1 on 2020-12-10 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201210_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetstatus',
            name='name',
            field=models.TextField(default=django.utils.timezone.now, max_length=2000, verbose_name='Полное наименование'),
            preserve_default=False,
        ),
    ]
