# Generated by Django 3.1 on 2020-12-10 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_budgetstatus_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glavbudgetclass',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glavs', to='api.budgetstatus', verbose_name='Бюджет'),
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
