# Generated by Django 3.1 on 2020-12-10 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201210_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetstatus',
            name='parentcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.budgetstatus', verbose_name='Вышестоящий бюджет'),
        ),
    ]
